### ISSUE TITLE
Need to remove gulp-util dependency

### ISSUE THREAD

**Issue by carl-utter** [OverZealous/run-sequence#102]
**Per this [article](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5):** this is a request to remove gulp-util using the following API replacements:

- gutil.File => [https://www.npmjs.com/package/vinyl](https://www.npmjs.com/package/vinyl)
- gutil.replaceExtension => The .extname property on Vinyl objects or [https://www.npmjs.com/package/replace-ext](https://www.npmjs.com/package/replace-ext)
- gutil.colors => [https://www.npmjs.com/package/ansi-colors](https://www.npmjs.com/package/ansi-colors)
- gutil.date => [https://www.npmjs.com/package/date-format](https://www.npmjs.com/package/date-format)
- gutil.log => [https://www.npmjs.com/package/fancy-log](https://www.npmjs.com/package/fancy-log)
- gutil.template => [https://www.npmjs.com/package/lodash.template](https://www.npmjs.com/package/lodash.template)
- gutil.env => [https://www.npmjs.com/package/minimist](https://www.npmjs.com/package/minimist)
- gutil.beep => [https://www.npmjs.com/package/beeper](https://www.npmjs.com/package/beeper)
- gutil.noop => [https://www.npmjs.com/package/through2](https://www.npmjs.com/package/through2)
- gutil.isStream => Use the .isStream() method on Vinyl objects
- gutil.isBuffer => Use the .isBuffer() method on Vinyl objects
- gutil.isNull => Use the .isNull() method on Vinyl objects
- gutil.linefeed => Use the string '\n' in your code
- gutil.combine => [https://www.npmjs.com/package/multipipe](https://www.npmjs.com/package/multipipe)
- gutil.buffer => [https://www.npmjs.com/package/list-stream](https://www.npmjs.com/package/list-stream)
- gutil.PluginError => [https://www.npmjs.com/package/plugin-error](https://www.npmjs.com/package/plugin-error)

**Comment by carl-utter** [comment]
My bad, I should have checked your closed issues first. Sorry about that and thanks for contributing.

**Comment by OverZealous** [comment]
No worries, it happens. Have a good one!
