### ISSUE TITLE
del in sequence fail because previous task not ended

### ISSUE THREAD

**Issue by ClementGautier** [OverZealous/run-sequence#21]
Hi,

I'm trying to do a simple worflow in my gulpfile like this:

```javascript
var gulp = require('gulp');
var sequence = require('run-sequence');
var del = require('del');

gulp.task('task1', function() {  gulp.src('gulp-test/src/file').pipe(gulp.dest('gulp-test/dest')); });
gulp.task('task2', function() { del('gulp-test/dest/file'); });
gulp.task('build', function() { sequence('task1', 'task2'); });
```

Here is the test:

```bash
$ mkdir -p gulp-test/src
$ touch gulp-test/src/file
$ ls -R gulp-test/
gulp-test/:
    src
gulp-test/src:
    file
$ gulp build
[15:06:27] Starting 'build'...
[15:06:27] Starting 'task1'...
[15:06:27] Finished 'task1' after 3.94 ms
[15:06:27] Starting 'task2'...
[15:06:27] Finished 'task2' after 1.63 ms
[15:06:27] Finished 'build' after 6.82 ms
$ ls -R gulp-test/
gulp-test/:
    dest  src
gulp-test/dest:
    file
gulp-test/src:
    file
$ gulp task2
[15:06:38] Starting 'task2'...
[15:06:38] Finished 'task2' after 1.84 ms
$ ls -R gulp-test/
gulp-test/:
    dest  src
gulp-test/dest:
gulp-test/src:
    file
```

What I don't understand is why the file is not deleted during the build.
I'm new to node so I guess its a anyschronous issue (looks like the `gulp.dest` is executed after the end of the task1 task ) but I don't know how to solve the issue.

**Comment by OverZealous** [comment]
Please [read the gulp documentation](https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support).  You do not have your tasks configured correctly.

You don't need `run-sequence` just to run two tasks in a row, only if you have two tasks that cannot depend on each other.

**Comment by ClementGautier** [comment]
Ok I lied, I have a much more complex build task actually with multiple tasks in the sequence but this case sum up the issue

**Comment by ClementGautier** [comment]
@OverZealous thx for the fast answer btw

**Comment by ClementGautier** [comment]
I reproduce the same issue replacing run-sequece by gulp task dependency as well so I admit that it's not a run-sequence issue but if someone know how to perform this he would be welcomed :)

**Comment by OverZealous** [comment]
I linked you to the solution: your tasks are configured incorrectly.  You have to either return the pipe, return a promise, or accept and use a callback.  Please read the gulp docs above.

(I am not a maintainer of gulp.)

**Comment by ClementGautier** [comment]
@OverZealous  Oh sorry I did not understood your answer. Thanks a lot
