### ISSUE TITLE
Possible to pass on a function as a parameter instead of a valid task string?

### ISSUE THREAD

**Issue by binarykitchen** [OverZealous/run-sequence#22]
Can I do something like this?

```js
  runSequence(
    'setFast',
    'webpack',
    function(cb) {
      // do something here
    }
    cb
  )
```

Asking this because I do not want to pollute my gulp file with unnecessary task I am not going to call from the outside.

Any ideas?

**Comment by OverZealous** [comment]
No, the purpose of run-sequence is to run gulp tasks, in a sequence.  It uses gulp's orchestrator to manage when tasks start and stop, it does not handle it on it's own.

You can namespace your gulp tasks if you have a lot.  I have 30+ tasks in one of my bigger files, I just use a naming convention like `styles:foo:build` or `scripts:bar:dist` for subtasks.

**Comment by binarykitchen** [comment]
thanks, good advice
