### ISSUE TITLE
Use with watch / on change?

### ISSUE THREAD

**Issue by royduin** [OverZealous/run-sequence#24]
Hi,

How to use this with gulp watch and a on change? Currently I've this watcher:

```
gulp.watch([config.templatePath+'/**/*','!'+config.templatePath+'/assets/stylesheets/**/*']).on('change', function(file) {
	browsersync.reload(file);
});
```

And I'd like to run the "build" task before the reload:

```
gulp.task('build', function() {
	return gulp
		.src(config.projectFile)
		.pipe(msbuild({
			toolsVersion: 12.0
		}));
});
```

So the reload will be fired after the build task is finished. Adding the build like this doesn't work (it doesn't wait for the build task to complete):

```
gulp.watch([config.templatePath+'/**/*','!'+config.templatePath+'/assets/stylesheets/**/*'],['build']).on('change', function(file) {
	browsersync.reload(file);
});
```

So I think I need run-sequence for this?

**Comment by OverZealous** [comment]
I'm not really sure how to help you on this one, this is not really related to run-sequence.

Run-sequence runs gulp tasks in a given order, that's all it does.  I use `gulp-watch` (the plugin), not `gulp.watch`, so I don't have any advice for how to use it in this scenario.

I always trigger BrowserSync from the tail end of the build tasks themselves, not separately, and I use an incremental build (I don't rebuild the entire app), so I can easily trigger a single file to reload.

Sorry!

**Comment by royduin** [comment]
Thanks for your reply, I'll search further.
