### ISSUE TITLE
run-sequence doesn't wait for child tasks run-sequences to complete

### ISSUE THREAD

**Issue by gajewsk2** [OverZealous/run-sequence#25]
How can I get 
```js
gulp.task('build', function () {
  runSequence('clean', 'main', 'task-dependent-on-main');
});

gulp.task('main', function () {
  runSequence('task1', 'task2');
});
```

to actually synchronously wait? Is there a way to get runSequence to return a stream so parent runSequence's know to wait? Right now it just blows past main and on to 'task-dependent-on-main', instead of completing 'task1' and 'task2'. Obviously, I could write them all in one runSequence:
```js
  runSequence('clean', 'task1', 'task2', 'task-dependent-on-main');
```
But they are split between files and that doesn't seem very clean.

**Comment by OverZealous** [comment]
As shown in the [docs](https://github.com/OverZealous/run-sequence#usage), just use the callback function:

```js
gulp.task('main', function (callback) {
  runSequence('task1', 'task2', callback);
});
```

This will only work if your tasks themselves are correctly configured.
