### ISSUE TITLE
Using this with merge-stream

### ISSUE THREAD

**Issue by sean-hill** [OverZealous/run-sequence#26]
Hey there, I'm using gulp to manage my email templates.

I have a task like this that adds a main CSS file to all my templates.

	gulp.task('emails-template-styles', function() {

		console.log('emails-template-styles');

		var templateFolders = getFolders(emailTemplateDir);

		var tasks = templateFolders.map(function(folder) {
			return gulp.src(masterEmailCssDirPath + '/style.css')
					   .pipe(gulp.dest(emailTemplateDir + '/' + folder))
		});

		return merge(tasks);

	});

I then use this task, along with a few others to build my entire email system using `run-sequence` as such

	// Emails task
	gulp.task('emails', function(){
		runSequence('emails-css', 'emails-templates', 'emails-template-styles');
	});

But as you can see, these tasks DO NOT run in order.

	[13:29:16] Starting 'emails'...
	[13:29:16] Starting 'emails-css'...
	emails-css
	[13:29:16] Finished 'emails-css' after 4.43 ms
	[13:29:16] Starting 'emails-templates'...
	emails-templates
	[13:29:16] Finished 'emails' after 11 ms
	[13:29:16] Finished 'emails-templates' after 16 ms
	[13:29:16] Starting 'emails-template-styles'...
	emails-template-styles
	[13:29:16] Finished 'emails-template-styles' after 2.39 ms

The `emails` tasks finishes before the `emails-templates` and `emails-template-styles` finish.

This is unexpected behavior. Thanks for any help you can provide!

**Comment by OverZealous** [comment]
Your tasks are running in order.  The only reason the `emails` task completes is you didn't use the callback function:

```js
gulp.task('emails', function(cb){
    runSequence('emails-css', 'emails-templates', 'emails-template-styles', cb);
});
```

It's [the first example in the docs](https://github.com/OverZealous/run-sequence#usage).

**Comment by sean-hill** [comment]
@OverZealous how embarrassing for me. Thanks for posting that solution :) Now it properly runs in the correct order, however, my last task `emails-template-styles` when run individually takes ~17ms to complete, when run in order with `run-sequence` and other tasks it runs in ~5ms, and is not working properly. 

	// Copy main email style sheet to email template folders
	gulp.task('emails-template-styles', function() {

		var templateFolders = getFolders(emailTemplateDir);

		var tasks = templateFolders.map(function(folder) {

			return gulp.src(masterEmailCssDirPath + '/style.css')
					   .pipe(gulp.dest(emailTemplateDir + '/' + folder))
					   
		});

		return merge(tasks);

	});

The `style.css` file that should be copied ends up blank in `emailTemplateDir + '/' + folder`. Maybe the `merge-stream` module and `run-sequence` aren't happy with each other? 

I follow [this](https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-task-steps-per-folder.md) recipe.

**Comment by OverZealous** [comment]
I don't know what you want me to do, it's not run-sequence, run-sequence just calls into gulp, waits for gulp to finish a task.

**Comment by sean-hill** [comment]
No problem @OverZealous, thanks for the help!

**Comment by Jaygiri** [comment]
@sean-hill did you found the solution?

**Comment by sean-hill** [comment]
@Jaygiri this was a while back, and I can't remember what the solution was, but this is my current code I have for that gulp task.

    gulp.task('emails-template-styles', function() {

        console.log('emails-template-styles');

        var templateFolders = getFolders(emailTemplateDir);
        var masterCSSStream = fs.createReadStream(masterEmailCssDirPath + '/style.css');

        templateFolders.forEach(function(folder){

            if (folder === 'partials') {
                return;
            }

            var emailCSSFile = emailTemplateDir + '/' + folder + '/style.css';

            var masterCSSStream = fs.createReadStream(masterEmailCssDirPath + '/style.css');
            masterCSSStream.pipe(fs.createWriteStream(emailCSSFile));

        });

    });

Looks like I ended up using the `fs` native library instead.

**Comment by Jaygiri** [comment]
@sean-hill thank you for your quick response. I am too trying native library before going for gulpv4. Btw, gulp-sequence is also failing similarly with gulp-merge!!
