### ISSUE TITLE
missing gulp dependency

### ISSUE THREAD

**Issue by dbuezas** [OverZealous/run-sequence#27]
gulp is only required in devDependencies but used in `index.js` what makes this module throw an exception when used as a dependency of another module.

This is because gulp doesn't end up in node_modules if one doesn't explicitly do `npm install` inside this modules's folder (as it is a devDependency).

**Comment by OverZealous** [comment]
That's not how it is designed.  You install gulp in your project, and `run-sequence` uses your copy of gulp.  If it had it's own copy, it wouldn't work.

If you want to use run-sequence as a dependency of a another module, then that module needs to depend on gulp.  run-sequence only depends on gulp for the devDependencies because it needs it for testing.

**Comment by dbuezas** [comment]
`module.exports = runSequence.bind(null, require('gulp')); ` will always throw an exception if `gulp` is not present in `run-sequence/node_modules`.

As `npm install` won't install the dev dependencies of run-sequence when run-sequence is a dependency of another module, gulp will not be available for run-sequence although the requiring module has gulp for itself.

Your tests require gulp so you must have installed the dev dependencies before they won't be able to test this special case.

You are right that it doesn't make any sense for run-sequence to have its own gulp so you shouldn't do `require('gulp')` in your index.js as it will throw exception. 

The usual way of injecting gulp is to export a function that gets gulp as an argument. Check these 18.000+ examples:

https://github.com/search?utf8=%E2%9C%93&q=module.exports+%3D+function%28gulp%29&type=Code&ref=searchresults

It is true that it is a breaking change, but hey, we've got semver :)

**Comment by OverZealous** [comment]
There are literally thousands of users using run-sequence without error.  If gulp is installed by the module that is using run-sequence, it works.  If you are using it in some weird way that doesn't have gulp installed, then I'm sorry, but I'm not interested in fixing that.

I already export a method (in use by others) that allows you to pass in a different instance of gulp.  It's not worth complicating the usage of a fairly simple and widely used library, for this one case.

**Comment by dbuezas** [comment]
Ok, I see your position. We just forked.
for the record it breaks when used in combination with `node link` because of this issue: https://github.com/joyent/node/issues/4757

It is a typical use case when developing a module required by a working project to avoid having to commit, push, pull to test if things work.

For anybody else having this problem, the solution is just to remove the `require('gulp')` or surround it in a try catch clause as in https://github.com/antwerpes/run-sequence.

Thanks for your work
