### ISSUE TITLE
Callback called too early

### ISSUE THREAD

**Issue by dizlexik** [OverZealous/run-sequence#28]
In this case:
`runSequence('one', ['two', 'three'], callback)`

`callback` should be called only after both `two` and `three` have completed, but instead it gets called as soon as the first of these completes. In other words, if `two` takes 1 second and `three` takes 5 seconds, `callback` will be called after 1 second.

**Comment by OverZealous** [comment]
This means you have your tasks incorrectly configured.  Please read the documentation for run-sequence and gulp again.

**Comment by dizlexik** [comment]
You're right, my bad. In one of my other tasks I was using run-sequence and was returning it instead of using the callback to determine when it was finished. If you get a chance, returning a Promise might not be a bad idea.
