### ISSUE TITLE
Using 'task_err' event

### ISSUE THREAD

**Issue by volkhv** [OverZealous/run-sequence#31]
There is not so much documentation about using 'task_err' event that user can call like this 

`task.emit('task_err', err)`

At first I thought that it is undocumented inner feature, but the code doesn't enit it itself. It is possible to make a situation with `task_err` clearer?

**Comment by OverZealous** [comment]
I don't understand what the question is here.  This doesn't seem to be related to `run-sequence`.

**Comment by volkhv** [comment]
When I am trying to interrupt whole sequence in the process of execution then `task.emit('task_err', err)` is only one possible way, as I understand. It works and I think that this method can be useful for others and I would like to see this method in the docs.

Or may be there is another way to interrupt sequence of task in the process of execution?

**Comment by OverZealous** [comment]
I don't know why you'd want to interrupt a sequence—it should automatically stop if any task throws an error, which is a gulp or node issue.

**Comment by markstos** [comment]
I'm using the `gulp-less` plugin with `run-sequence`. `gulp-less` is running into an error with invalid `less`, but the sequence keeps on running. It's not clear if `gulp-less` plugin is not behaving properly, or if `run-quence` isn't stopping the sequence as expected.

**Comment by markstos** [comment]
My issues with gulp-less and run-sequence turned out to be a general design  issue with how `gulp` handles errors, not any one particular plugin. This issue from `gulp-typescript` discusses it more:

https://github.com/ivogabe/gulp-typescript/issues/295
