### ISSUE TITLE
e36a6069 needs to be published on npm, thanks!

### ISSUE THREAD

**Issue by caitp** [OverZealous/run-sequence#32]
Before e36a6069, `runSequence(referenceToSomeArray)` would modify the array and break on subsequent uses.

Instead of working around this by cloning arrays on input, it would be fantastic if you published a new release =)

Cheers

**Comment by OverZealous** [comment]
It is published, version 1.1.0.  I don't understand what you are asking.

**Comment by caitp** [comment]
yeah, you're right --- the newest tag in this repo doesn't have it, got confused. Thanks

**Comment by OverZealous** [comment]
Ah, I see the confusion.  I deleted the GitHub-specific release, which was hiding (!) the other tags.

Just an FYI: the primary source for actual releases is NPM.
