### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by nicky-lenaers** [OverZealous/run-sequence#34]
I get the following message when using gulp-run-sequence:
``gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.``
Can this be fixed?

**Comment by OverZealous** [comment]
[`gulp-run-sequence` has been deprecated for a _very_ long time.](https://www.npmjs.com/package/gulp-run-sequence)  You are on `run-sequence`, which replaced it.  Please replace it with `run-sequence` and update to the latest version.

**Comment by nicky-lenaers** [comment]
Thank you for the update!
