### ISSUE TITLE
Can run-sequence return a promise?

### ISSUE THREAD

**Issue by peterjwest** [OverZealous/run-sequence#35]
Most gulp streams return a promise so you can write:

```
gulp.task('standards', function() {
    return gulp.src(['foo.js']).pipe(jscs());
});
```

and gulp uses the promise to tell when the task is complete.

Can `run-sequence` support this?

**Comment by OverZealous** [comment]
No, `run-sequence` and gulp both support using a callback, and this works fine for it's intended purpose.  I love promises, I just have no intention of adding them to this library.
