### ISSUE TITLE
A usage question (callbacks)

### ISSUE THREAD

**Issue by zagortenay333** [OverZealous/run-sequence#38]
Hey, complete noob to nodejs. After hours of googling I gotta ask here.

```js
gulp.task('install', function (done) {
    fs.mkdir(..., function(){})
    fs.unlink(..., function(){})
    fs.symlink(..., function(){})
    done();
});


gulp.task('reloadTheme', shell.task([
    '...',
    '...'
]));


gulp.task('default', function(done) {
    sequence('install', 'reloadTheme', done);
});
```

From what I could figure out, I need the `install` task to run async so that the task system knows when it finished?

Am I using the done callback in the install task correctly? Is it even necessary, or have I completely missed the point?

Also, is there any point to the `done` callback in the default task? Without it, `default` will not wait for `install` nor `reloadTheme` to finish, but does it have to anyway?

**Comment by OverZealous** [comment]
This really isn't the right place to ask this—you've got a lot completely wrong here at a node level.  Just about every call to a function in Node is _asynchronous_ by default.  This means all your `fs.` methods are going to be called asynchronously, and most likely won't complete before the next function is called.

You are going to have to do some more reading and learning, there's just too many things for me to help with here, and really none of it has anything to do with `run-sequence`.

The part using run-sequence itself is correct, though, with the callback method.

**Comment by zagortenay333** [comment]
OK, thanks!
