### ISSUE TITLE
gulp.watch only runs once when passed a run-sequence task

### ISSUE THREAD

**Issue by tonyeung** [OverZealous/run-sequence#42]
http://stackoverflow.com/questions/31593582/gulp-watch-only-runs-once-when-passed-a-run-sequence-task

I have a [gulpfile](https://github.com/tonyeung/angular-gulp-bower-seed/blob/master/gulpfile.js), it uses run sequence and gulp.watch().

When I make a change to a file, the watch task will run the task I specified exactly once. In this case, the task that should be executed is "run", which is the same as the default task except it doesn't run the dev server and watch task again. Nothing happens when I make further edits, whether in the same file or a different one, for example, the [index.html](https://github.com/tonyeung/angular-gulp-bower-seed/blob/master/src/app/common/templates/index.html) file

If I pass gulp.watch a plain gulp task (without run sequence), for example the clean task, then the watch will run the clean task every time.

I'm sure I'm doing something wrong, but I don't understand what. I think something might be silently erroring and disconnecting the stream, but I can't figure out how to debug this.

**Comment by OverZealous** [comment]
You aren't passing the callback into run-sequence, therefore the task never completes.

**Comment by tonyeung** [comment]
omg i spent so much time on this, thanks so much.
