### ISSUE TITLE
Silent error on undefined

### ISSUE THREAD

**Issue by TrySound** [OverZealous/run-sequence#43]
I'd like to use conditional tasks. It would be nice to add this feature.
```js
run(env.clean ? 'clean' : undefined, function () {});
```

**Comment by TrySound** [comment]
Maybe better pass this error in callback?

**Comment by TrySound** [comment]
Resolved with promises
```
new Promise(function (resolve) {
	if(env.clean) {
		run('clean', resolve);
	} else {
		resolve();
	}
}).then(function () {
	run(['script', 'style', 'markup', 'sprite', 'image', 'font'], function () {
		done();
	});
});
```

**Comment by OverZealous** [comment]
You are making this overly complicated.  Just put an `if` block around your `run-sequence`.

```js
if(env.clean) {
    run('clean', done);
} else {
   done();
}
```

I will not be removing the error on invalid task names (or empty task names).

**Comment by TrySound** [comment]
@OverZealous My decision is about processing assets after optional clean.

**Comment by OverZealous** [comment]
@TrySound That doesn't change my answer.  You can also use `apply` and an array to call run-sequence with an unknown number of parameters.
