### ISSUE TITLE
Callback error

### ISSUE THREAD

**Issue by TrySound** [OverZealous/run-sequence#44]
I think callback should be called after executing parallel tasks

Here I'd like to call done after all tasks executed even with error.
```js
run(['script', 'style', 'markup', 'sprite', 'image', 'font'], function () {
	done();
});
```

**Comment by OverZealous** [comment]
Run sequence does not handle errors, this is up to your code.  If your task fails, it is assumed there is no recovery, otherwise you would have caught and handled the error yourself.

**Comment by TrySound** [comment]
@OverZealous run-sequence shouldn't handle errors, but it responses for sequence executing tasks. Even with error in one task it should response for another tasks.
I suggets to pass in callback first erorr. Can I make PR for this?

**Comment by OverZealous** [comment]
@TrySound No, that's not how it works.  If you want to capture errors within your tasks, you need to capture them _within_ the task itself.

run-sequence simply calls the tasks in the order specified.  If a [stream error occurs, it _does_ pass that back to the callback](https://github.com/OverZealous/run-sequence/blob/master/index.js#L53).
