### ISSUE TITLE
using a dynamic list of gulp tasks in run-sequence

### ISSUE THREAD

**Issue by scottnath** [OverZealous/run-sequence#47]
I am creating some gulp tasks with dynamic task names. *These tasks need to be run in order, not parallel.* I am putting the task names in an array, but I am getting an error from run-sequence. I assume this error is a problem with how I am listing the tasks from the array in my run-sequence code.

## This is an example what I'm doing

1. Create an array of task names

    `var taskNames = ['task1', 'task2', 'task3']`

2. Print them out for run sequence to use in order
    ```
    gulp.task('run-dynamic-tasks', function(){
      runSequence(
        taskNames.join(", \n"),
        function(){
          browserSync.reload();
        }
      );
    });
    ```

3. This does not work and gives this error:
    ```
    Error: Task task1,
    task2,
    task3 is not configured as a task on gulp. If this is a submodule (error continues)
    ```

## This *does* work if there is only one task in the array, such as:

`var taskNames = ['task1'];`

then this code works and the single task is run.

I believe this is probably a javascript mistake, as opposed to run-sequence or node, but I thought I'd check here in case this use-case has caused issues before.

thank you for any and all help, Scott

**Comment by OverZealous** [comment]
> ```
> taskNames.join(", \n"),
> ```

This does not create an array.  This creates a string, with the names separated by a comma, a space, and a newline.  What the heck were you trying to do here?

If you want to dynamically call a function, use `Function.prototype.apply`.

**Comment by scottnath** [comment]
Hey @OverZealous,

I'm trying to use a dynamic list of task names inside of run sequence. My goal is this:

```
    gulp.task('run-dynamic-tasks', function(){
      runSequence(
        task1,
        task2,
        task3,
        function(){
          browserSync.reload();
        }
      );
    });
```

Because the gulp task names are created according to other variables, I can't just write them in the runcSequence list.

My list of task names are currently in an array:

`var taskNamesArray = ['task1', 'task2', 'task3']`

But, I **can't** put them in runSequence as an array like this:

 ```
    gulp.task('run-dynamic-tasks', function(){
      runSequence(
        taskNamesArray,
        function(){
          browserSync.reload();
        }
      );
    });
```
because that will run the tasks in parallel, not in order.

**Comment by OverZealous** [comment]
I explained above, please take a moment to research `Function.prototype.apply`, which is pretty basic JavaScript.

It'll look something like this:

```js
runSequence.apply(null, [].concat(taskNamesArray, function() { ... });
```

For basic JavaScript questions and usage, StackOverflow is a more appropriate resource.

**Comment by ugogo** [comment]
I think, what @scottnath wanted to do, is to add **dynamically** a task into `runSequence`.

Something like:
```js
gulp.task('myTask', function () {
  runSequence('a', 'b', condition ? 'c' : '');
});
```

(But runSequence doesn't accept empty value.)

**Comment by OverZealous** [comment]
@ugogo That has nothing to do with the issue at hand.  You can dynamically call any function from JavaScript with an previously unkown list of arguments using `fn.apply`.  The example I provide above explains it.

You example would be:

```js
gulp.task('myTask', function () {
    var tasks = ['a', 'b'];
    if(condition) {
        tasks.push('c');
    }
    runSequence.apply(null, tasks);
});
```

No, it's not as clean, but it works.  You can also always put the condition within your task if the task itself does not have any standard dependencies.

**Comment by scottnath** [comment]
Thanks @OverZealous and @ugogo, this is indeed a simple javascript solution that I was totally missing.

Final solution is this:

```
    gulp.task('run-dynamic-tasks', function(){
      runSequence.apply(null, taskNamesArray);
    });
```
