### ISSUE TITLE
gulp.watch ?

### ISSUE THREAD

**Issue by binarykitchen** [OverZealous/run-sequence#5]
Could we do the same for `gulp.watch`?

Like this:

``` js
gulp.watch('something', runSequence('build-clean', ['build-scripts', 'build-styles'], 'build-html'));
```

That would be awesome!

**Comment by yairEO** [comment]
@cworsley4 - it works fine for me. here's how I set it up: http://stackoverflow.com/a/34873271/104380

**Comment by yairEO** [comment]
Actually, there's a problem with it. now, when there is an error in some task, seems `watch` is not working anymore, so when I fix the issue, gulp just hangs and nothing happens after the problem has been reported. very annoying I have to run `gulp` again every time there's a problem

**Comment by slavafomin** [comment]
This would be a very convenient feature, why is it closed?

**Comment by OverZealous** [comment]
Because it has nothing to do with this library, which simply runs gulp tasks in order when called.

There's also 2 solutions above that suffice, both of which are 2 line of code or less.
