### ISSUE TITLE
Is the use of the "del" package supported in runSequence?

### ISSUE THREAD

**Issue by af7** [OverZealous/run-sequence#50]
I use the following "del" task, as the **1st task** in a sequence:

````
gulp.task('clean', function (cb) {
       return del('./myDir');
});
````

It appears that this makes **everything else** in the sequence **not to run**.

What am I doing wrong? Is this supported?

Thanks!

**Comment by OverZealous** [comment]
You aren't calling the callback, so `gulp` thinks the task never completes.

**Comment by af7** [comment]
Wow, that was really fast, thanks!

Would you care to explain (if it is easy, so that we all understand the logic) why the "return" of the "del" is not sufficient? I thought that "del" returns a promise and that should be OK. Obviously not, but why?

Thanks again!

**Comment by OverZealous** [comment]
It's because you specified the callback.  If you include the argument, gulp assumes you will call it.  If you want to return a promise or stream, you **cannot** include the callback argument.  (gulp checks your task's `Function.length` property to see if you have requested a callback or not.)

**Comment by af7** [comment]
Thanks, this is **very** helpful explanation for others not the get into this "trap" also. Respect to your support.

**Comment by OverZealous** [comment]
You're welcome!
