### ISSUE TITLE
Doing this with gulp itself

### ISSUE THREAD

**Issue by gunar** [OverZealous/run-sequence#55]
Hi, there!

Scrolling through `gulp`'s repo, I found that there's a way to [run tasks in series and parallel with task's depedencies](https://github.com/gulpjs/gulp/blob/master/docs/recipes/running-tasks-in-series.md).

Or am I missing something? It worked here with Gulp 3.9.0.

Anyway, thanks for `run-sequence`. It's very handy.

**Comment by OverZealous** [comment]
First line in the README explains this:

> Runs a sequence of gulp tasks in the specified order. This function is designed to solve the situation where you have defined run-order, but **choose not to or cannot use dependencies.**
