### ISSUE TITLE
Issue using the plugin :-( 

### ISSUE THREAD

**Issue by eyeamaman** [OverZealous/run-sequence#58]
It started with cannot find module 'chalk'.

After adding chalk & gulp-util to devDependencies in node_modules/run-sequence/package.json and running `$ npm install` within the same folder.  It came up with this error

``` Error: Task build-all is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp) ```

the code

``` Javascript
gulp.task('default', function() {
  runSequence('build-all', ['htmlclean', 'iconfont'], 'styles');
});
```

Is this a brand new issue? :-S
and is it possible to add chalk and gulp-util to the devDependencies so lazy folk like myself don't have to install it :-D

**Comment by OverZealous** [comment]
I don't have any issue.  I recommend completely deleting `node_modules` and re-running `npm install`. I've had similar errors in the past, and that fixed it.  You should remove the extra dependencies.  They are automatically added via `gulp-util`.

Nothing has been changed in `run-sequence` in a while, it should still work just fine.  I have not tested it under NPM 3 (and have no near-term plans to).

**Comment by eyeamaman** [comment]
Okay I'll run through the basics today and see what happens. I also think I'm using npm 2.14.7 but will have to look when I get home.

**Comment by OverZealous** [comment]
@eyeamaman I haven't heard back from you, so I'll assume everything is OK.  Feel free to reopen if you are continuing to have issues.
