### ISSUE TITLE
Error when passing empty string 

### ISSUE THREAD

**Issue by yairEO** [OverZealous/run-sequence#64]
I randomly (gulp works until it suddenly decides to stop and crash) get an error message, after adding lines like this: (using a optional gulp-util env variable when running `gulp --test`)

    gulp.watch('templates/**/*.html', function(){ runSequence('templates', 'bundleJS', gutil.env.test ? 'tests' : '') });

### Error output: 

    C:\www\project\node_modules\ttf2woff2\jssrc\ttf2woff2.js:1
    (function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?
    Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Modul
    e[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var
    ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;
    var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!M
    odule["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printEr
    r"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["
    read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"](filenam

    Error: Task  is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').u
    se(gulp).
        at C:\www\project\node_modules\run-sequence\index.js:20:10
        at Array.forEach (native)
        at verifyTaskSets (C:\www\project\node_modules\run-sequence\index.js:13:11)
        at runSequence (C:\www\project\node_modules\run-sequence\index.js:94:2)
        at C:\www\project\gulpfile.js:515:51
        at Gaze.<anonymous> (C:\www\project\node_modules\glob-watcher\index.js:18:14)
        at emitTwo (events.js:100:13)
        at Gaze.emit (events.js:185:7)
        at Gaze.emit (C:\www\project\node_modules\gaze\lib\gaze.js:129:32)
        at C:\www\project\node_modules\gaze\lib\gaze.js:415:16
        at StatWatcher._pollers.(anonymous function) (C:\www\project\node_modules\gaze\lib\gaze.js:326:7)
        at emitTwo (events.js:100:13)
        at StatWatcher.emit (events.js:185:7)
        at StatWatcher._handle.onchange (fs.js:1369:10)

I think there is some problem here... is this run-sequence related?

**Comment by OverZealous** [comment]
It's working as expected, it even tells you the error.  You can only pass valid tasks to `runSequence`.

Note: This is not getting changed.

**Comment by yairEO** [comment]
may I ask if it's a lot of work to ignore `null` or empty strings? maybe I can hack it if you will say it can be quickly done..

**Comment by OverZealous** [comment]
I've already had this discussion with others.  I'm not changing the library to ignore invalid tasks.

**Comment by OverZealous** [comment]
Hey, I know this is an older issue, but just to let you know, I added this in as an option, but you have to opt-in to the behavior.

Please see the [new Options section in the readme](https://github.com/OverZealous/run-sequence#options), thanks.
