### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by Cactucs** [OverZealous/run-sequence#65]
Run-sequence is passing only some of the information from failed tasks. It would be better to pass whole `e` when [creating `PluginError`](https://github.com/OverZealous/run-sequence/blob/master/index.js#L56-L58) 

Maybe something like this:
```
var err = new gutil.PluginError('test', existingError, {showStack: true});
```
_Source: [gulp-utils readme file](https://github.com/gulpjs/gulp-util#new-pluginerrorpluginname-message-options)_

**Comment by OverZealous** [comment]
If you pass the gulp callback to run-sequence as the final argument, it should get printed correctly.

Otherwise, I'll look at a PR, but this isn't a big enough issue that I'm going to fix it any time soon.

**Comment by Cactucs** [comment]
If I pass callback I get only in which task the error was, but not the message from the original error.
