### ISSUE TITLE
Gulp merge breaking with run sequence

### ISSUE THREAD

**Issue by raghvendrabajpai92** [OverZealous/run-sequence#67]
If there are 4 tasks to be run and first task is having return merge, only first task is run.

**Comment by OverZealous** [comment]
What?

**Comment by Jaygiri** [comment]
@raghvendrabajpai92 did you found the solution?

**Comment by divisble** [comment]
I know it's old thread but working solution is:
`gulp.task('less', function (cb) { // <-- callback func
    var files = [];
    for (var key in paths.less) {
        var src = gulp.src(paths.less[key])
// all pipes here
        files.push(src);
    }
    cb(); // <-- callback
    return merge(files);
});`
