### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by miguel-leon** [OverZealous/run-sequence#78]
As of Gulp 3.9.1, the following example mentioned in the readme for this project does not work.
```javascript
gulp.task('build', function(callback) {
runSequence('build-clean',
		  ['build-scripts', 'build-styles'],
		  'build-html',
		  callback);
});
```
`callback` is not called and tasks are started but not finished. Found explanation here: https://github.com/robrich/orchestrator/issues/15

I know the readme mentions that using this is a hack, and it uses deprecated methods that may not work as expected. I'm just pointing it out because it may save some time to people following the example and expecting it to work.

**Comment by OverZealous** [comment]
Are your gulp tasks correctly set up? Because it they aren't configured correctly, then they never complete, and if they don't complete, the callback is never called.

`runSequence` still works for me without issue on `3.9.1`

**Comment by miguel-leon** [comment]
I'm sorry for the promptly allegation.
I tested a much more simplified version and it worked. Upon further analysis it seems it is having problems but with [gulp-require-tasks](https://github.com/betsol/gulp-require-tasks) and the tasks split into multiple files.
Maybe it has something to do with [orchestrator](https://github.com/robrich/orchestrator)'s `runTask` depending on `Function.length`.

If it's no longer pertinent. Please, remove the issue.
And thanks for the quick response.

**Comment by OverZealous** [comment]
Ah, yeah, Gulp requires Function.length for the return.

Glad you could figure it out!
