### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by uyouthe** [OverZealous/run-sequence#86]
Hello.

Here's the piece of my gulpfile:
```JavaScript
gulp.task('default', function () {
	runSequence(
		'css',
		'html'
	);
});
```
You can see it's pretty simple.

My CSS task assemblies all CSS files into `bundle.css`, and my HTML task inlines it into HTML. When I make the changes to CSS files and run `gulp`, the changes are not appear at the end file. To ensure that run-sequence doesn't work, I added one more task that deletes `bundle.css` before running `css` task, and I got the `ENOENT: no such file or directory, open '...\bundle.css'`, that pretty much proves that `bundle.css` hasn't been created. Here's my full gulpfile:
[gulpfile.txt](https://github.com/OverZealous/run-sequence/files/835057/gulpfile.txt)

**Comment by uyouthe** [comment]
Maybe I'm missing something? Let me know please!

**Comment by OverZealous** [comment]
Please [read the docs again](https://github.com/OverZealous/run-sequence#usage): your tasks are not correctly set up, so they are returning immediately. You need to configure them to be asynchronous.

**Comment by uyouthe** [comment]
omg, sorry
