### ISSUE TITLE
package.json by using require('run-sequence').use(gulp);

### ISSUE THREAD

**Issue by jgoknowis** [OverZealous/run-sequence#88]
const runSequence = require('run-sequence').use(gulp);

How do i have to cite the dependencies in my package.json

package.json
```
"devDependencies": {
    "run-sequence": "1.2.2"
}

```
actually i get this in my build log
```
08:52:13 [ERROR] module.js:471
08:52:13 [ERROR]     throw err;
08:52:13 [ERROR]     ^
08:52:13 [ERROR] 
08:52:13 [ERROR] Error: Cannot find module 'run-sequence'
```

**Comment by OverZealous** [comment]
This seems like an NPM/Node issue. Make sure you've installed your dependencies.

**Comment by jgoknowis** [comment]
U can see in package.json with collect all dependencies is run-squence. but nevertheless i get the error. All other dependencies have no problem with that.
