### ISSUE TITLE
Risky dependency

### ISSUE THREAD

**Issue by CExAdamJ** [OverZealous/run-sequence#90]
There are hidden breaking changes creeping into this module because of the way it has defined its dependencies.

https://github.com/OverZealous/run-sequence/blob/master/package.json#L26

Can you please tag against a specific version of `chalk`? Preferably one before chalk v2.0.0 and one after as this is a major breaking change and drops support for older versions of Node.

**Comment by AdamWills** [comment]
I have issued a PR to fix this - hoping we get a quick response!

#89

**Comment by OverZealous** [comment]
v.2.0.0 has been released. Thanks!
