### ISSUE TITLE
Error Stack Trace

### ISSUE THREAD

**Issue by roend83** [OverZealous/run-sequence#92]
Outputting the stack trace on error [here](https://github.com/OverZealous/run-sequence/blob/master/index.js#L56) is causing my build output to be totally useless when there are nested run-sequence tasks.  I'm getting thousands of lines of stack trace outputted.  Is there an easy way to turn this off?  I'd be happy to send a PR to make this configurable or off by default.

**Comment by OverZealous** [comment]
Hey there!

I'll be honest, that line has been modified back and forth so many times, I don't really want to change it too much. I'll look at an easy way to configure it.

Would you be OK with a global configuration, so changing it one place changes it everywhere that `runSequence` is used? I envision a usage like this:

```js
var runSequence = require('run-sequence');
runSequence.configure({ showErrorStackTrace: false });
```

This way I could store a simple hash of configuration options and not have to deal with per-usage configuration. This would also open the door to some other options people have wanted, without making everything too complicated.

**Comment by roend83** [comment]
That sounds fantastic. Would you like me to send a PR?

**Comment by OverZealous** [comment]
Nah, I know how I want to handle this, so I'll see if I can get it built tonight. I've got some other non-code things I want to make changes to at the same time.

**Comment by OverZealous** [comment]
OK, should be published now. Just pull down `v2.1.0`.

It's even a bit simpler, just do `runSequence.options.showErrorStackTrace = false;` to suppress those changes.
